/**
 * @file     tpm.h (180.ARM_Peripherals/Project_Headers/tpm.h)
 * @brief    Flexitimer Timer Module
 *
 * @version  V4.12.1.80
 * @date     13 April 2016
 *      Author: podonoghue
 */
#ifndef HEADER_TPM_H
#define HEADER_TPM_H

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */
#include <stddef.h>
#include <cmath>
#include "pin_mapping.h"

/*
 * Default port information
 */
namespace USBDM {

/**
 * @addtogroup TPM_Group TPM, PWM, Input capture and Output compare
 * @brief Pins used for PWM, Input capture and Output compare
 * @{
 */

/**
 * Callback to catch unhandled channel interrupt
 *
 * @param mask Mask identifying channel
 */
void timerUnhandledChannelCallback(uint8_t);

/**
 * Type definition for timer overflow interrupt call back
 */
typedef void (*TpmCallbackFunction)();

/**
 * Provides shared methods.
 */
class TpmBase {

private:
   TpmBase(const TpmBase&) = delete;
   TpmBase(TpmBase&&) = delete;

public:

   /** Class to static check channel exists - it does not check that it is mapped to a pin */
   template<class Info, int channel> class CheckChannel {
      // Tests are chained so only a single assertion can fail so as to reduce noise

      // Out of bounds value for function index
      static constexpr bool Test1 = (channel>=0) && (channel<(Info::numSignals));
      // Non-existent function
      static constexpr bool Test2 = !Test1 || (Info::info[channel].gpioBit != INVALID_PCR);

      static_assert(Test1, "Illegal TPM channel - Check Configure.usbdm for available channels");
      static_assert(Test2, "TPM channel doesn't exist in this device/package - Check Configure.usbdm for available channels");

   public:
      /** Dummy function to allow convenient in-line checking */
      static constexpr void check() {}
   };

   /** Class to static check channel exists and is mapped to a pin */
   template<class Info, int channel> class CheckChannelExistsAndMapped {
      // Tests are chained so only a single assertion can fail so as to reduce noise

      // Out of bounds value for function index
      static constexpr bool Test1 = (channel>=0) && (channel<(Info::numSignals));
      // Function is not currently mapped to a pin
      static constexpr bool Test2 = !Test1 || (Info::info[channel].gpioBit != UNMAPPED_PCR);
      // Non-existent function and catch-all. (should be INVALID_PCR)
      static constexpr bool Test3 = !Test1 || !Test2 || (Info::info[channel].gpioBit >= 0);

      static_assert(Test1, "Illegal TPM channel - Check Configure.usbdm for available inputs");
      static_assert(Test2, "TPM input is not mapped to a pin - Modify Configure.usbdm");
      static_assert(Test3, "TPM channel doesn't exist in this device/package - Check Configure.usbdm for available input pins");

   public:
      /** Dummy function to allow convenient in-line checking */
      static constexpr void check() {}
   };

   /** Class to static check channel is mapped to a pin - Ignores non-existence etc. */
   template<class Info, int channel> class CheckChannelIsMappedToPinOnly {

      // Out of bounds value for function index
      static constexpr bool Test1 = (channel>=0) && (channel<(Info::numSignals));
      // Function is not currently mapped to a pin
      static constexpr bool Test2 = !Test1 || (Info::info[channel].gpioBit != UNMAPPED_PCR);

      static_assert(Test2, "TPM channel is not mapped to a pin - Modify Configure.usbdm");

   public:
      /** Dummy function to allow convenient in-line checking */
      static constexpr void check() {}
   };

protected:
   // Constructor
   constexpr TpmBase(uint32_t baseAddress) : tpm(baseAddress) {};
   ~TpmBase() = default;

   /** Allow access owning TPM */
   const HardwarePtr<TPM_Type> tpm;

   /**
    * Limit index to permitted pin index range
    * Used to prevent noise from static assertion checks that detect a condition already detected in a more useful fashion.
    *
    * @tparam Inf    Associated info table
    * @param index   Index to limit
    *
    * @return Index limited to permitted range
    */
   template <class Inf>
   static inline constexpr int limitIndex(int index) {
      if (index<0) {
         return 0;
      }
      if (index>(Inf::numSignals-1)) {
         return Inf::numSignals-1;
      }
      return index;
   }

   /**
    * Callback to catch unhandled interrupt
    */
   static void unhandledCallback() {
      setAndCheckErrorCode(E_NO_HANDLER);
   }

   /**
    * Get Timer input frequency.
    *
    * @param tpmClockSource
    *
    * @return Clock frequency in Hz
    */
   virtual float getInputClockFrequencyVirtual(TpmClockSource tpmClockSource) const = 0;

public:
   /**
    * Structure for TPM channel.
    */
   struct TpmChannelRegs {
      __IO uint32_t  CnSC; /**< 000C: Channel  Status and Control */
      __IO uint32_t  CnV;  /**< 0010: Channel  Value              */
   };

/*
 *   // Member functions (mirrored)
 */
   /**
    * Stop timer counter.
    * This simply disables the counter clock source. 

    * To restart use setClockSource() or configure();
    *
    * @note This function will affect all channels of the timer.
    * @note A illegal access trap will occur if the timer has not been enabled
    */
   void stopCounter() const {
     tpm->SC = (tpm->SC&~TPM_SC_PS_MASK);
   }
   
   /**
    * Set Clock Source and Clock prescaler
    *
    * @param tpmClockSource Selects the clock source for the module
    * @param tpmPrescale    Selects the prescaler for the module
    */
   void selectClock(
         TpmClockSource tpmClockSource,
         TpmPrescale    tpmPrescale) const {
   
      // Calculate new SC value
      uint32_t sc = (tpm->SC&~(TPM_SC_CMOD_MASK|TPM_SC_PS_MASK))|(tpmClockSource|tpmPrescale);
   
      // Disable timer to change clock (unable to switch directly between clock sources)
      tpm->SC=0;
   
      // Make sure write has completed (disabled)
      (void)(tpm->SC);
   
      // Write new value
      tpm->SC = sc;
   }

   /**
    * Set Alignment and whether interval or free-running mode
    *
    * @param tpmMode Left-aligned   (0...mod) or
    *        Centre-aligned (0...mod...0) or
    *        Free-running   (0...maximum_value)
    *
    * @note This function will affect all channels of the timer.
    * @note The timer will be disabled while making changes.
    */
   void setMode(TpmMode tpmMode) const {
   
      // Calculate new SC value
      uint32_t sc = (tpm->SC&~(TPM_SC_TOF_MASK|TPM_SC_CPWMS_MASK))|(tpmMode);

      // Disable timer to change clock (unable to switch directly between clock sources)
      tpm->SC=0;

      // Make sure write has completed (disabled)
      (void)(tpm->SC);

      // Write new value
      tpm->SC = sc;
   }
   
   /**
    * Get Alignment and whether interval or free-running mode
    *
    * @param tpmMode Left-aligned   (0...mod) or
    *        Centre-aligned (0...mod...0) or
    *        Free-running   (0...maximum_value)
    */
   TpmMode getMode() const {
   
      return (TpmMode)(tpm->SC&~(TPM_SC_TOF_MASK|TPM_SC_CPWMS_MASK));
   }

   /**
    * Set Clock Source
    *
    * @param tpmClockSource Selects the clock source for the module
    *
    * @note This function will affect all channels of the timer.
    * @note The timer will be disabled while making changes.
    */
   void setClockSource(TpmClockSource tpmClockSource) const {
   
      // Calculate new SC value
      uint32_t sc = (tpm->SC&~TPM_SC_CMOD_MASK)|(tpmClockSource);

      // Disable timer to change clock (unable to switch directly between clock sources)
      tpm->SC=0;

      // Make sure write has completed (disabled)
      (void)(tpm->SC);

      // Write new value
      tpm->SC = sc;
   }
   
   /**
    * Get Clock Source
    *
    * @param tpmClockSource Selects the clock source for the module
    */
   TpmClockSource getClockSource() const {
   
      return (TpmClockSource)(tpm->SC&~TPM_SC_CMOD_MASK);
   }

   /**
    * Set Clock prescaler
    *
    * @param tpmPrescale Selects the prescaler for the module
    *
    * @note This function will affect all channels of the timer.
    * @note The timer will be disabled while making changes.
    */
   void setPrescaler(TpmPrescale tpmPrescale) const {
   
      // Calculate new SC value
      uint32_t sc = (tpm->SC&~TPM_SC_PS_MASK)|(tpmPrescale);

      // Disable timer to change clock (unable to switch directly between clock sources)
      tpm->SC=0;

      // Make sure write has completed (disabled)
      (void)(tpm->SC);

      // Write new value
      tpm->SC = sc;
   }
   
   /**
    * Get Clock prescaler
    *
    * @param tpmPrescale Selects the prescaler for the module
    */
   TpmPrescale getPrescaler() const {
   
      return (TpmPrescale)(tpm->SC&~TPM_SC_PS_MASK);
   }

   /**
    * Set End value for counter
    * This value is write-buffered and updated by MOD synchronisation
    *
    * @param ticks   The timer counts from 0 to this value
    *
    * @note This function will affect all channels of the timer.
    */
   void setCounterMaximumValue(Ticks   ticks) const {
   
      // Write new value
      tpm->MOD = ticks;
   }
   
   /**
    * Get End value for counter
    *
    * @param ticks   The timer counts from 0 to this value
    */
   Ticks getCounterMaximumValue() const {
   
      return (Ticks)tpm->MOD;
   }

   /**
    * Calculate TPM timing parameters to achieve a given period
    *
    * @param[in]    period  Period in seconds
    * @param[inout] sc      Proposed TPM.SC value (must include CLKS, CPWMS fields)
    *                       PS field is updated
    * @param[out]   mod     Calculated TPM.MOD values
    *
    * @return E_NO_ERROR   Success!!
    * @return E_TOO_SMALL  Requested period is too small for resolution (required resolution check to be enabled)
    * @return E_TOO_LARGE  Requested period is too large
    */
   ErrorCode calculateTimingParameters(Seconds period, uint8_t &sc, uint16_t &mod) const {
   
      float inputClock = getInputClockFrequencyVirtual((TpmClockSource)(sc&TPM_SC_CMOD_MASK));
      unsigned prescaleFactor=1;
      unsigned prescalerValue=0;
   
      // Check if CPWMS is set (affects period calculation)
      bool centreAligned = (sc&TPM_SC_CPWMS_MASK);
   
      constexpr uint32_t maxModValue = TPM_MOD_MOD_MASK;
   
      while (prescalerValue<=7) {
         float clock    = inputClock/prescaleFactor;
         float modValueF = period*clock;
         if (centreAligned) {
            // PeriodInTicks = 2*MOD
            modValueF = modValueF/2;
         }
         else {
            // PeriodInTicks = MOD+1
            modValueF = modValueF - 1;
         }
         unsigned modValue = round(modValueF);
         if (modValue <= maxModValue) {
            sc   = (sc&~TPM_SC_PS_MASK)|TPM_SC_PS(prescalerValue);
            mod  = modValue;
            return E_NO_ERROR;
         }
         prescalerValue++;
         prescaleFactor <<= 1;
      }
      // Too long a period
      usbdm_assert(false, "Interval is too long");
      return setErrorCode(E_TOO_LARGE);
   }

   /**
    * Set period
    *
    * @param[in] period   Period in seconds as a float
    *
    * @return E_NO_ERROR  => success
    * @return E_TOO_SMALL  Requested period is too small for resolution (required resolution check to be enabled).
    * @return E_TOO_LARGE  Requested period is too large.
    *
    * @note This function will affect all channels of the timer.
    * @note Adjusts Timer pre-scaler to appropriate value.
    * @note The counter load value (CNTIN) is cleared
    * @note The counter modulo value (MOD) is modified to obtain the requested period
    * @note The Timer is stopped while being modified.
    * @note The Timer counter is restarted from zero
    */
   ErrorCode setPeriod(Seconds period) const {
   
      uint16_t modValue = 0;
   
      uint8_t sc = tpm->SC;
   
      ErrorCode rc = calculateTimingParameters(period, sc, modValue);
   
      if (rc != E_NO_ERROR) {
         return rc;
      }
      // Disable timer to change prescaler and period
      tpm->SC = 0;
   
      // Configure for modulo operation
      tpm->MOD   = modValue;
   
      // Clear counter
      tpm->CNT   = 0;
   
      // Set prescale and enable timer
      tpm->SC  = sc;
   
      return E_NO_ERROR;
   }
   
   /**
    * Set maximum interval for input-capture or output compare.
    * Input Capture and Output Compare will be able to operate over
    * at least this period without overflow.
    *
    * @param[in] interval Interval in seconds as a float
    *
    * @return E_NO_ERROR  => success
    * @return E_TOO_SMALL  Requested period is too small for resolution (required resolution check to be enabled).
    * @return E_TOO_LARGE  Requested period is too large.
    *
    * @note This function will affect all channels of the timer.
    * @note Adjusts Timer pre-scaler to appropriate value.
    * @note TPM counter is configured for free-running mode i.e. 0-65535
    * @note The Timer is stopped while being modified.
    * @note The Timer counter is restarted from zero
    */
   ErrorCode setMaximumInterval(Seconds interval) const {
   
      uint16_t       modValue;
   
      uint8_t sc = tpm->SC;
   
      ErrorCode rc = calculateTimingParameters(interval, sc, modValue);
      if (rc != E_NO_ERROR) {
         return rc;
      }
   
      // Disable timer to change prescaler and period
      tpm->SC = 0;
   
      // Configure for free-running mode
      // This is the usual value for IC or OC set-up
      tpm->MOD   = 0_ticks;
   
      // Clear counter
      tpm->CNT   = 0;
   
      // Set prescale and enable timer
      tpm->SC  = sc;
   
      return E_NO_ERROR;
   }

   /**
    * Get frequency of timer tick
    *
    * @return Timer frequency in Hz
    */
   float getTickFrequencyAsFloat() const {
   
      // Calculate timer prescale factor
      float prescaleFactor = 1<<((tpm->SC&TPM_SC_PS_MASK)>>TPM_SC_PS_SHIFT);
   
      return getInputClockFrequencyVirtual((TpmClockSource)(tpm->SC&TPM_SC_CMOD_MASK))/prescaleFactor;
   }
   
   /**
    * Get clock frequency
    *
    * @return Frequency as a uint32_t in Hz (may underflow)
    */
   uint32_t getTickFrequencyAsInt() const {
   
      // Calculate timer prescale factor
      int prescaleFactor = 1<<((tpm->SC&TPM_SC_PS_MASK)>>TPM_SC_PS_SHIFT);
   
      return getInputClockFrequencyVirtual((TpmClockSource)(tpm->SC&TPM_SC_CMOD_MASK))/prescaleFactor;
   }

   /**
    * Convert time in microseconds to time in ticks
    *
    * @param[in] time Time in microseconds
    *
    * @return Time in ticks
    *
    * @note Assumes prescale has been chosen as a appropriate value. Rudimentary range checking.
    * @note Will set error code if calculated value is less the Timer minimum resolution
    */
   Ticks convertMicrosecondsToTicks(int time) const {
   
      // Calculate period
      uint32_t tickRate = getTickFrequencyAsInt();
      uint64_t rv       = (static_cast<uint64_t>(time)*tickRate)/1000000;
      usbdm_assert(rv <= 0xFFFFUL, "Interval is too long");
      if (rv > 0xFFFFUL) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      return (unsigned)rv;
   }
   
   /**
    * Converts time in seconds to time in ticks
    *
    * @param[in] seconds Time interval in seconds
    *
    * @return Time in ticks
    *
    * @note Assumes prescale has been chosen as a appropriate value (see setMaximumInterval()). 

    * @note Will set error code if calculated value is less the minimum resolution
    */
   Ticks convertSecondsToTicks(Seconds seconds) const {
   
      // Calculate period
      float    tickRate = getTickFrequencyAsFloat();
      uint64_t rv       = rintf((float)seconds*tickRate);
      usbdm_assert(rv <= 0xFFFFUL, "Interval is too long");
      if (rv > 0xFFFFUL) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      return (unsigned)rv;
   }
   
   /**
    * Convert time in ticks to time in microseconds
    *
    * @param[in] timeInTicks Time in ticks
    *
    * @return Time in microseconds
    *
    * @note Assumes prescale has been chosen as a appropriate value. Rudimentary range checking.
    */
   uint32_t convertTicksToMicroseconds(Ticks timeInTicks) const {
   
      // Calculate period
      uint64_t rv = (static_cast<uint64_t>((unsigned)timeInTicks)*1000000)/getTickFrequencyAsInt();
#ifdef DEBUG_BUILD
      if (rv > 0xFFFFUL) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      if (rv == 0) {
         // Attempt to set too short a period
         setErrorCode(E_TOO_SMALL);
      }
#endif
      return rv;
   }
   
   /**
    * Convert time in ticks to time in milliseconds
    *
    * @param[in] timeInTicks Time in ticks
    *
    * @return Time in milliseconds
    *
    * @note Assumes prescale has been chosen as a appropriate value. Rudimentary range checking.
    */
   uint32_t convertTicksToMilliseconds(Ticks timeInTicks) const {
   
      // Calculate period
      uint64_t rv = (static_cast<uint64_t>((unsigned)timeInTicks)*1000)/getTickFrequencyAsInt();
#ifdef DEBUG_BUILD
      if (rv > 0xFFFFUL) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      if (rv == 0) {
         // Attempt to set too short a period
         setErrorCode(E_TOO_SMALL);
      }
#endif
      return rv;
   }
   
   /**
    * Convert time in ticks to time in seconds
    *
    * @param[in] timeInTicks Time in ticks
    *
    * @return Time in seconds
    */
   Seconds convertTicksToSeconds(Ticks timeInTicks) const {
      return static_cast<float>((unsigned)timeInTicks)/getTickFrequencyAsFloat();
   }
   /**
    * Get Timer count
    *
    * @return Timer count value
    */
   uint16_t getTime() const {
      return tpm->CNT;
   }

   /**
    * Reset counter to initial value
    */
   void resetTime() const {
      // Note: writing ANY value loads CNT from CNTIN
      tpm->CNT = 0;
   }
   
   /**
    * Get timer event flags
    *
    * @return Flags indicating if an event has occurred on a channel
    *         There is one bit for each channel
    */
   unsigned getInterruptFlags() const {
      return tpm->STATUS;
   }
   
   /**
    * Clear selected timer event flags
    *
    * @param channelMask Mask indicating which channel flags to clear
    *                    There is one bit for each channel
    *
    * @note Flags will not be cleared if the channel is configured for DMA
    */
   void clearSelectedInterruptFlags(uint32_t channelMask) const {
      (void)tpm->STATUS;
      tpm->STATUS = ~channelMask;
   }
   
   /**
    * Get and clear timer event flags
    *
    * @return Flags indicating if an event has occurred on a channel
    *         There is one bit for each channel
    *
    * @note Only flags captured in the return value are cleared
    * @note Flags will not be cleared if the channel is configured for DMA
    */
   unsigned getAndClearInterruptFlags() const {
      // Note - w1c flags
      // so only flags captured in status are cleared
      unsigned status = tpm->STATUS;
      tpm->STATUS = status;
      return status;
   }
   /**
    * Enable/disable Timer Overflow interrupts
    */
   void enableTimerOverflowInterrupts() const {
      tpm->SC = tpm->SC | TPM_SC_TOIE_MASK;
   }
   
   /**
    * Disable Timer Overflow interrupts
    */
   void disableTimerOverflowInterrupts() const {
      tpm->SC = tpm->SC & ~TPM_SC_TOIE_MASK;
   }

   /*
    * *****************************************************************
    *          Channel functions
    * *****************************************************************
    */
   /**
    * Set PWM duty cycle.
    * Higher precision float version
    *
    * @param[in] dutyCycle  Duty-cycle as percentage (float)
    * @param[in] channel    Timer channel
    *
    * @note The actual CnV register update may be delayed by the register synchronisation mechanism
    */
   void setDutyCycle(float dutyCycle, int channel) const {
      if (tpm->SC&TPM_SC_CPWMS_MASK) {
         tpm->CONTROLS[channel].CnV  = round((dutyCycle*tpm->MOD)/100.0f);
      }
      else {
         tpm->CONTROLS[channel].CnV  = round((dutyCycle*(tpm->MOD+1))/100.0f);
      }
   }
   
   /**
    * Set PWM duty cycle
    *
    * @param[in] dutyCycle  Duty-cycle as percentage
    * @param[in] channel    Timer channel
    *
    * @note The actual CnV register update may be delayed by the register synchronisation mechanism
    */
   void setDutyCycle(int dutyCycle, int channel) const {
      if (tpm->SC&TPM_SC_CPWMS_MASK) {
         tpm->CONTROLS[channel].CnV  = (dutyCycle*tpm->MOD)/100;
      }
      else {
         tpm->CONTROLS[channel].CnV  = (dutyCycle*(tpm->MOD+1))/100;
      }
   }
   
   /**
    * Set PWM high time in ticks
    * Assumes value is less than period
    *
    * @param[in] highTime   PWM high time in ticks
    * @param[in] channel    Timer channel
    *
    * @return E_NO_ERROR on success
    * @return E_TOO_LARGE on success
    *
    * @note The actual CnV register update may be delayed by the register synchronisation mechanism
    */
   ErrorCode setHighTime(Ticks highTime, int channel) const {
   
      if (tpm->SC&TPM_SC_CPWMS_MASK) {
         // In CPWM the pulse width is doubled
         highTime = (highTime+1_ticks)/2U;
      }
#ifdef DEBUG_BUILD
      if ((unsigned)highTime > tpm->MOD) {
         return setErrorCode(E_TOO_LARGE);
      }
#endif
      tpm->CONTROLS[channel].CnV  = (unsigned)highTime;
      return E_NO_ERROR;
   }
   
   /**
    * Get Timer event time
    *
    * @param[in] channel    Timer channel
    *
    * @return Absolute time of last event in ticks i.e. value from timer event register
    */
   Ticks getEventTime(int channel) const {
      return (unsigned)(tpm->CONTROLS[channel].CnV);
   }
   
   /**
    * Set Timer event time
    *
    * This value is write-buffered and updated by Cnv synchronisation.
    *
    * @param[in] eventTime  Absolute event time in ticks i.e. value to use as timer comparison value
    * @param[in] channel    Timer channel
    */
   void setEventTime(Ticks eventTime, int channel) const {
      tpm->CONTROLS[channel].CnV = (unsigned)eventTime;
   }
   
   /**
    * Set Timer event time relative to current event time
    *
    * @param[in] offset     Event time in ticks relative to current event time (i.e. Timer channel CnV value)
    * @param[in] channel    Timer channel
    *
    * @note This value is write-buffered and updated by CnV synchronisation.
    */
   void setDeltaEventTime(Ticks offset, int channel) const {
      tpm->CONTROLS[channel].CnV = tpm->CONTROLS[channel].CnV + (unsigned)offset;
   }
   
   /**
    * Set Timer event time relative to current timer count value
    *
    * @param[in] offset     Event time in ticks relative to current time (i.e. Timer CNT value)
    * @param[in] channel    Timer channel
    *
    * @note This value is write-buffered and updated by CnV synchronisation.
    */
   void setRelativeEventTime(Ticks offset, int channel) const {
      tpm->CONTROLS[channel].CnV = tpm->CNT + (unsigned)offset;
   }
   
   /**
    * Set PWM high time in seconds
    *
    * @param[in] highTime   PWM high time in seconds
    * @param[in] channel    Timer channel
    *
    * @return E_NO_ERROR on success
    *
    * @note The actual CnV register update may be delayed by the TPM register synchronisation mechanism
    */
   ErrorCode setHighTime(Seconds highTime, int channel) const {
      return setHighTime(convertSecondsToTicks(highTime), channel);
   }
   
};

class TpmChannel : public TpmBase {

private:
   TpmChannel(const TpmChannel&) = delete;
   TpmChannel(TpmChannel&&) = delete;

protected:
   // Empty constructor
   constexpr TpmChannel(uint32_t baseAddress, unsigned channelNum) :
   TpmBase(baseAddress),
   channelRegs((uint32_t)(tpm->CONTROLS+channelNum)),
   CHANNEL(channelNum),
   CHANNEL_MASK(1<<channelNum) {
   }
   ~TpmChannel() = default;

public:
   /** Allow access to TPM channel registers */
   const HardwarePtr<TpmBase::TpmChannelRegs> channelRegs;

   /** Timer channel number */
   const unsigned CHANNEL;

   /** Mask for Timer channel */
   const uint32_t CHANNEL_MASK;

   
      /**
       * Set Action on Channel Event
       *
       * @param tpmChannelAction Enable interrupt on channel event
       *
       * @note This method has the side-effect of clearing the register update synchronisation i.e.
       *       pending CnV register updates are discarded.
       */
       void setAction(TpmChannelAction tpmChannelAction) const {
         tpm->CONTROLS[CHANNEL].CnSC = (tpm->CONTROLS[CHANNEL].CnSC & ~TPM_CnSC_CHIE_MASK) | tpmChannelAction;
      }

      /**
       * Configure channel.
       * No affect on shared settings of owning Timer
       *
       * @param[in] tpmChannelMode    Mode of operation for channel
       * @param[in] tpmChannelAction  Whether to enable the interrupt or DMA function on this channel
       *
       * @note This method has the side-effect of clearing the register update synchronisation i.e.
       *       pending CnV register updates are discarded.
       */
       void configure(
            TpmChannelMode    tpmChannelMode,
            TpmChannelAction  tpmChannelAction = TpmChannelAction_None) const {
   
         tpm->CONTROLS[CHANNEL].CnSC = tpmChannelMode|tpmChannelAction;
      }
   
      /**
       * Disables timer channel (sets mode to TpmChannelMode_Disabled)
       */
       void disable() const {
         setMode(TpmChannelMode_Disabled);
      }
   
      /**
       * Get channel mode.
       *
       * @return Current mode of operation for the channel
       */
       TpmChannelMode getMode() const {
         return static_cast<TpmChannelMode>(tpm->CONTROLS[CHANNEL].CnSC &
               (TPM_CnSC_MS_MASK|TPM_CnSC_ELS_MASK));
      }
   
      /**
       * Set channel mode
       *
       * @param[in] tpmChannelMode      Mode of operation for channel
       *
       * @note This method has the side-effect of clearing the register update synchronisation i.e.
       *       pending CnV register updates are discarded.
       */
       void setMode(TpmChannelMode tpmChannelMode) const {
         tpm->CONTROLS[CHANNEL].CnSC =
               (tpm->CONTROLS[CHANNEL].CnSC & ~(TPM_CnSC_MS_MASK|TPM_CnSC_ELS_MASK))|tpmChannelMode;
      }
   
      /**
       * Set PWM high time in ticks.
       * Assumes value is less than period
       *
       * @param[in] highTime   PWM high time in ticks
       *
       * @return E_NO_ERROR on success
       *
       * @note The actual CnV register update will be delayed by the register synchronisation mechanism
       */
       ErrorCode setHighTime(Ticks highTime) const {
         return TpmBase::setHighTime(highTime, CHANNEL);
      }
   
      /**
       * Set PWM high time in seconds.
       * Higher precision float version
       *
       * @param[in] highTime   PWM high time in seconds
       *
       * @return E_NO_ERROR on success
       *
       * @note The actual CnV register update will be delayed by the register synchronisation mechanism
       */
       ErrorCode setHighTime(Seconds highTime) const {
         return TpmBase::setHighTime(highTime, CHANNEL);
      }
      /**
       * Set PWM duty cycle.
       *
       * @param[in] dutyCycle  Duty-cycle as percentage
       *
       * @note The actual CnV register update will be delayed by the register synchronisation mechanism
       */
       void setDutyCycle(int dutyCycle) const {
         TpmBase::setDutyCycle(dutyCycle, CHANNEL);
      }
   
      /**
       * Set PWM duty cycle
       *
       * @param[in] dutyCycle  Duty-cycle as percentage
       *
       * @note The actual CnV register update will be delayed by the register synchronisation mechanism
       */
       void setDutyCycle(float dutyCycle) const {
         TpmBase::setDutyCycle(dutyCycle, CHANNEL);
      }
   
      /**
       * Set Timer event time.
       *
       * @param[in] offset  Event time in ticks relative to current event time (i.e. Timer channel CnV value)
       *
       * @note The actual CnV register update will be delayed by the register synchronisation mechanism
       */
       void setDeltaEventTime(Ticks offset) const {
         TpmBase::setDeltaEventTime(offset, CHANNEL);
      }
   
      /**
       * Set Timer event time relative to current timer count value.
       *
       * @param[in] offset  Event time in ticks relative to current time (i.e. Timer CNT value)
       *
       * @note The actual CnV register update will be delayed by the register synchronisation mechanism
       */
       void setRelativeEventTime(Ticks offset) const {
         TpmBase::setRelativeEventTime(offset, CHANNEL);
      }
   
      /**
       * Set Absolute Timer event time.
       *
       * @param[in] eventTime  Absolute event time in ticks i.e. value to use as timer comparison value
       *
       * @note The actual CnV register update will be delayed by the register synchronisation mechanism
       */
       void setEventTime(Ticks eventTime) const {
         TpmBase::setEventTime(eventTime, CHANNEL);
      }
   
      /**
       * Get Absolute Timer event time.
       *
       * @return Absolute time of last event in ticks i.e. value from timer event register
       */
       Ticks getEventTime() const {
         return TpmBase::getEventTime(CHANNEL);
      }
   
      /**
       * Get Timer interrupt/event flag.
       *
       * @return true  Indicates an event has occurred on a channel
       * @return false Indicates no event has occurred on a channel since last polled
       */
       bool getInterruptFlag() const {
         return (tpm->STATUS&CHANNEL_MASK) != 0;
      }
   
      /**
       * Get and Clear Timer channel interrupt flag.
       *
       * @return true  Indicates an event has occurred on a channel
       * @return false Indicates no event has occurred on a channel since last polled
       *
       * @note Only flags captured in the return value are cleared
       */
       bool getAndClearInterruptFlag() const {
         // Note - w1c flags
         // so only flags captured in status are cleared
         bool status = (tpm->STATUS&CHANNEL_MASK) != 0;
         tpm->STATUS = CHANNEL_MASK;
         return status;
      }
   
      /**
       * Clear interrupt flag on channel.
       */
       void clearInterruptFlag() const {
         // Note - w1c flags
         tpm->CONTROLS[CHANNEL].CnSC = TPM_CnSC_CHF_MASK;
      }



};

/**
 * Base class representing a TPM.
 *
 *
 * @tparam Info  Class describing TPM hardware instance
 */
template<class Info>
class TpmBase_T : public TpmBase, public Info {

private:
   /**
    * This class is not intended to be instantiated
    */
   TpmBase_T(const TpmBase_T&) = delete;
   TpmBase_T(TpmBase_T&&) = delete;

   typedef typename Info::ChannelCallbackFunction ChannelCallbackFunction;

public:

   // Empty constructor
   constexpr TpmBase_T() : TpmBase(Info::baseAddress) {}
   virtual ~TpmBase_T() = default;

   /** Maximum counter value in ticks */
   static constexpr Ticks MaximumPeriodInTicks = TPM_MOD_MOD_MASK;

   /** Hardware instance pointer */
   static constexpr HardwarePtr<TPM_Type> tpm = Info::baseAddress;

   /** @return Base address of TPM hardware as uint32_t */
   static constexpr uint32_t tpmBase() { return Info::baseAddress; }
   /** @return Base address of TPM.SC register as uint32_t */
   static constexpr uint32_t tpmSC() { return tpmBase() + offsetof(TPM_Type, SC); }
   /** @return Base address of TPM.CNT register as uint32_t */
   static constexpr uint32_t tpmCNT() { return tpmBase() + offsetof(TPM_Type, CNT); }
   /** @return Base address of TPM.MOD register as uint32_t */
   static constexpr uint32_t tpmMOD() { return tpmBase() + offsetof(TPM_Type, MOD); }
   /** @return Base address of TPM.CONTROL[n] struct as uint32_t */
   static constexpr uint32_t tpmCONTROL(int index) { return tpmBase() + offsetof(TPM_Type, CONTROLS) + index*sizeof(TPM_Type::CONTROLS[0]); }
   /** @return Base address of TPM.CONTROL[n].CnSC struct as uint32_t */
   static constexpr uint32_t tpmCnSC(int index) { return tpmBase() + offsetof(TPM_Type, CONTROLS) + index*sizeof(TPM_Type::CONTROLS[0])+0; }
   /** @return Base address of TPM.CONTROL[n].CnV struct as uint32_t */
   static constexpr uint32_t tpmCnV(int index) { return tpmBase() + offsetof(TPM_Type, CONTROLS) + index*sizeof(TPM_Type::CONTROLS[0])+sizeof(uint32_t); }

private:
   /** Callback function for Channel Fault and timer overflow */
   static typename Info::CallbackFunction sCallback;

   /** Number of channels mapped to a channel event vector */
   static constexpr unsigned ChannelVectorRatio = Info::NumChannels/Info::NumChannelVectors;

protected:
   /**
    * Get frequency of timer tick
    *
    * @return Timer frequency in Hz
    */
   virtual float getInputClockFrequencyVirtual(TpmClockSource tpmClockSource) const override {
      return Info::getInputClockFrequency(tpmClockSource);
   }

public:
   /**
    * Common IRQ handler
    */
   static void irqHandler() {
      // Check of TOF set and enabled
      if ((tpm->SC&(TPM_SC_TOF_MASK|TPM_SC_TOIE_MASK)) == (TPM_SC_TOF_MASK|TPM_SC_TOIE_MASK)) {
         // Clear TOI flag (w1c)
         tpm->SC = tpm->SC | TPM_SC_TOF_MASK;
         sCallback();
      }
      else {
         // Get status for channels
         uint32_t status = tpm->STATUS;
         if (status) {
            // Clear flags for channel events being handled (w1c register if read)
            tpm->STATUS = status;
            Info::channelCallbacks[0](status);
         }
      }
   }

   /**
    * Wrapper to allow the use of a class member as a callback function
    * @note Only usable with static objects.
    *
    * @tparam T         Type of the object containing the callback member function
    * @tparam callback  Member function pointer
    * @tparam object    Object containing the member function
    *
    * @return  Pointer to a function suitable for the use as a callback
    *
    * @code
    * class AClass {
    * public:
    *    int y;
    *
    *    // Member function used as callback
    *    // This function must match ChannelCallbackFunction
    *    void callback(uint8_t status) {
    *       ...;
    *    }
    * };
    * ...
    * // Instance of class containing callback member function
    * static AClass aClass;
    * ...
    * // Wrap member function
    * auto fn = Tpm0::wrapCallback<AClass, &AClass::callback, aClass>();
    * // Use as callback
    * Tpm0::setCallback(fn);
    * @endcode
    */
   template<class T, void(T::*callback)(uint8_t), T &object>
   static ChannelCallbackFunction wrapCallback() {
      static ChannelCallbackFunction fn = [](uint8_t status) {
         (object.*callback)(status);
      };
      return fn;
   }

   /**
    * Wrapper to allow the use of a class member as a callback function
    * @note There is a considerable space and time overhead to using this method
    *
    * @tparam T         Type of the object containing the callback member function
    * @tparam callback  Member function pointer
    * @tparam object    Object containing the member function
    *
    * @return  Pointer to a function suitable for the use as a callback
    *
    * @code
    * class AClass {
    * public:
    *    int y;
    *
    *    // Member function used as callback
    *    // This function must match ChannelCallbackFunction
    *    void callback(uint8_t status) {
    *       ...;
    *    }
    * };
    * ...
    * // Instance of class containing callback member function
    * AClass aClass;
    * ...
    * // Wrap member function
    * auto fn = Tpm0::wrapCallback<AClass, &AClass::callback>(aClass);
    * // Use as callback
    * Tpm0::setCallback(fn);
    * @endcode
    */
   template<class T, void(T::*callback)(uint8_t)>
   static ChannelCallbackFunction wrapCallback(T &object) {
      static T &obj = object;
      static ChannelCallbackFunction fn = [](uint8_t status) {
         (obj.*callback)(status);
      };
      return fn;
   }

   /**
    * Set common fault and Timer Overflow Callback function\n
    *
    * @param[in] theCallback Callback function to execute when timer overflows. \n
    *                        nullptr to indicate none
    */
   static void setCallback(typename Info::CallbackFunction theCallback) {
      static_assert(Info::irqHandlerInstalled, "TPM not configured for interrupts - Modify Configure.usbdm");
      if (theCallback == nullptr) {
         sCallback = unhandledCallback;
         return;
      }
      sCallback = theCallback;
   }

public:
// Template _mapPinsOption.xml

   /**
    * Configures all mapped pins associated with TPM
    *
    * @note Locked pins will be unaffected
    */
   static void configureAllPins() {
   
      // Configure pins if selected and not already locked
      if constexpr (Info::mapPinsOnEnable && !(MapAllPinsOnStartup || ForceLockedPins)) {
         Info::initPCRs();
      }
   }

   /**
    * Disabled all mapped pins associated with TPM
    *
    * @note Only the lower 16-bits of the PCR registers are modified
    *
    * @note Locked pins will be unaffected
    */
   static void disableAllPins() {
   
      // Disable pins if selected and not already locked
      if constexpr (Info::mapPinsOnEnable && !(MapAllPinsOnStartup || ForceLockedPins)) {
         Info::clearPCRs();
      }
   }

   /**
    * Basic enable of TPM
    * Includes enabling clock and configuring all mapped pins if mapPinsOnEnable is selected in configuration
    */
   static void enable() {
      Info::enableClock();
      configureAllPins();
   }

   /**
    * Disables the clock to TPM and all mapped pins
    */
   static void disable() {
      disableNvicInterrupts();
      tpm->SC = TPM_SC_CMOD(0);
      disableAllPins();
      Info::disableClock();
   }
// End Template _mapPinsOption.xml

   /**
    * Configure TPM from values specified in init
   
    * @param init Class containing initialisation values
    */
   static ErrorCode configure(const typename Info::Init &init) {
   
      // Enable peripheral clock and map pins
      enable();
   
      if constexpr (Info::irqHandlerInstalled) {
         // Only set call-back if feature enabled and non-null
         if (init.callbackFunction != nullptr) {
            setCallback(init.callbackFunction);
         }
         enableNvicInterrupts(init.irqlevel);
      }
      uint8_t  sc    = init.sc;
      uint16_t mod   = init.mod;
   
      if (init.modperiod != 0) {
   
         // Calculate sc.ps, mod (assumes cntin=0)
         ErrorCode rc = calculateTimingParameters(init.modperiod, sc, mod);
         if (rc != E_NO_ERROR) {
            return rc;
         }
      }
      if (init.sc&TpmMode_FreeRunning) {
         // Make free-running
         mod   = TPM_MOD_MOD_MASK;
      }
      // Disable timer to change clock (unable to switch directly between clock sources)
      tpm->SC  = 0;
   
      // End value for counter
      tpm->MOD = mod;
   
      // Restart counter
      tpm->CNT = 0;
   
      // Configure timer
      tpm->SC  = sc;
   
      return E_NO_ERROR;
   }


   /**
    * Configure Channel from values specified in channelInit
   
    * @param channelInit Class containing initialisation values
    */
   static ErrorCode configureChannel(const typename Info::ChannelInit &channelInit) {
   
      // Enable peripheral clock
      Info::enableClock();
   
      // Configure timer channel
      tpm->CONTROLS[channelInit.channel].CnV  = channelInit.cnv;
      tpm->CONTROLS[channelInit.channel].CnSC = channelInit.cnsc;
   
      return E_NO_ERROR;
   }


/*
 *   // Static functions (mirrored)
 */
   /**
    * Enables clock to peripheral and configures all pins.
    * Configures main operating settings for timer.
    *
    * @param tpmMode        Left-aligned   (0...mod) or
    *        Centre-aligned (0...mod...0) or
    *        Free-running   (0...maximum_value)
    * @param tpmClockSource Selects the clock source for the module
    * @param tpmPrescale    Selects the prescaler for the module
    */
   static void configure(
         TpmMode        tpmMode,
         TpmClockSource tpmClockSource,
         TpmPrescale    tpmPrescale    = TpmPrescale_DivBy1) {
   
      // Enable clock to peripheral
      enable();
   
      // Disable timer to change settings
      tpm->SC=0;
   
      // Make sure write has completed (disabled)
      (void)(tpm->SC);
   
      // Write new value
      tpm->SC = tpmMode|tpmClockSource|tpmPrescale;
   }

   /**
    * Stop timer counter.
    * This simply disables the counter clock source. 

    * To restart use setClockSource() or configure();
    *
    * @note This function will affect all channels of the timer.
    * @note A illegal access trap will occur if the timer has not been enabled
    */
   static void stopCounter() {
     tpm->SC = (tpm->SC&~TPM_SC_PS_MASK);
   }
   
   /**
    * Set Clock Source and Clock prescaler
    *
    * @param tpmClockSource Selects the clock source for the module
    * @param tpmPrescale    Selects the prescaler for the module
    */
   static void selectClock(
         TpmClockSource tpmClockSource,
         TpmPrescale    tpmPrescale) {
   
      // Calculate new SC value
      uint32_t sc = (tpm->SC&~(TPM_SC_CMOD_MASK|TPM_SC_PS_MASK))|(tpmClockSource|tpmPrescale);
   
      // Disable timer to change clock (unable to switch directly between clock sources)
      tpm->SC=0;
   
      // Make sure write has completed (disabled)
      (void)(tpm->SC);
   
      // Write new value
      tpm->SC = sc;
   }

   /**
    * Set Alignment and whether interval or free-running mode
    *
    * @param tpmMode Left-aligned   (0...mod) or
    *        Centre-aligned (0...mod...0) or
    *        Free-running   (0...maximum_value)
    *
    * @note This function will affect all channels of the timer.
    * @note The timer will be disabled while making changes.
    */
   static void setMode(TpmMode tpmMode) {
   
      // Calculate new SC value
      uint32_t sc = (tpm->SC&~(TPM_SC_TOF_MASK|TPM_SC_CPWMS_MASK))|(tpmMode);

      // Disable timer to change clock (unable to switch directly between clock sources)
      tpm->SC=0;

      // Make sure write has completed (disabled)
      (void)(tpm->SC);

      // Write new value
      tpm->SC = sc;
   }
   
   /**
    * Get Alignment and whether interval or free-running mode
    *
    * @param tpmMode Left-aligned   (0...mod) or
    *        Centre-aligned (0...mod...0) or
    *        Free-running   (0...maximum_value)
    */
   static TpmMode getMode() {
   
      return (TpmMode)(tpm->SC&~(TPM_SC_TOF_MASK|TPM_SC_CPWMS_MASK));
   }

   /**
    * Set Clock Source
    *
    * @param tpmClockSource Selects the clock source for the module
    *
    * @note This function will affect all channels of the timer.
    * @note The timer will be disabled while making changes.
    */
   static void setClockSource(TpmClockSource tpmClockSource) {
   
      // Calculate new SC value
      uint32_t sc = (tpm->SC&~TPM_SC_CMOD_MASK)|(tpmClockSource);

      // Disable timer to change clock (unable to switch directly between clock sources)
      tpm->SC=0;

      // Make sure write has completed (disabled)
      (void)(tpm->SC);

      // Write new value
      tpm->SC = sc;
   }
   
   /**
    * Get Clock Source
    *
    * @param tpmClockSource Selects the clock source for the module
    */
   static TpmClockSource getClockSource() {
   
      return (TpmClockSource)(tpm->SC&~TPM_SC_CMOD_MASK);
   }

   /**
    * Set Clock prescaler
    *
    * @param tpmPrescale Selects the prescaler for the module
    *
    * @note This function will affect all channels of the timer.
    * @note The timer will be disabled while making changes.
    */
   static void setPrescaler(TpmPrescale tpmPrescale) {
   
      // Calculate new SC value
      uint32_t sc = (tpm->SC&~TPM_SC_PS_MASK)|(tpmPrescale);

      // Disable timer to change clock (unable to switch directly between clock sources)
      tpm->SC=0;

      // Make sure write has completed (disabled)
      (void)(tpm->SC);

      // Write new value
      tpm->SC = sc;
   }
   
   /**
    * Get Clock prescaler
    *
    * @param tpmPrescale Selects the prescaler for the module
    */
   static TpmPrescale getPrescaler() {
   
      return (TpmPrescale)(tpm->SC&~TPM_SC_PS_MASK);
   }

   /**
    * Set End value for counter
    * This value is write-buffered and updated by MOD synchronisation
    *
    * @param ticks   The timer counts from 0 to this value
    *
    * @note This function will affect all channels of the timer.
    */
   static void setCounterMaximumValue(Ticks   ticks) {
   
      // Write new value
      tpm->MOD = ticks;
   }
   
   /**
    * Get End value for counter
    *
    * @param ticks   The timer counts from 0 to this value
    */
   static Ticks getCounterMaximumValue() {
   
      return (Ticks)tpm->MOD;
   }

   /**
    * Calculate TPM timing parameters to achieve a given period
    *
    * @param[in]    period  Period in seconds
    * @param[inout] sc      Proposed TPM.SC value (must include CLKS, CPWMS fields)
    *                       PS field is updated
    * @param[out]   mod     Calculated TPM.MOD values
    *
    * @return E_NO_ERROR   Success!!
    * @return E_TOO_SMALL  Requested period is too small for resolution (required resolution check to be enabled)
    * @return E_TOO_LARGE  Requested period is too large
    */
   static ErrorCode calculateTimingParameters(Seconds period, uint8_t &sc, uint16_t &mod) {
   
      float inputClock = Info::getInputClockFrequency((TpmClockSource)(sc&TPM_SC_CMOD_MASK));
      unsigned prescaleFactor=1;
      unsigned prescalerValue=0;
   
      // Check if CPWMS is set (affects period calculation)
      bool centreAligned = (sc&TPM_SC_CPWMS_MASK);
   
      constexpr uint32_t maxModValue = TPM_MOD_MOD_MASK;
   
      while (prescalerValue<=7) {
         float clock    = inputClock/prescaleFactor;
         float modValueF = period*clock;
         if (centreAligned) {
            // PeriodInTicks = 2*MOD
            modValueF = modValueF/2;
         }
         else {
            // PeriodInTicks = MOD+1
            modValueF = modValueF - 1;
         }
         unsigned modValue = round(modValueF);
         if (modValue < Info::minimumResolution) {
            usbdm_assert(false, "Interval is too short");
            // Too short a period for minimum resolution
            return setErrorCode(E_TOO_SMALL);
         }
         if (modValue <= maxModValue) {
            sc   = (sc&~TPM_SC_PS_MASK)|TPM_SC_PS(prescalerValue);
            mod  = modValue;
            return E_NO_ERROR;
         }
         prescalerValue++;
         prescaleFactor <<= 1;
      }
      // Too long a period
      usbdm_assert(false, "Interval is too long");
      return setErrorCode(E_TOO_LARGE);
   }

   /**
    * Set period
    *
    * @param[in] period   Period in seconds as a float
    *
    * @return E_NO_ERROR  => success
    * @return E_TOO_SMALL  Requested period is too small for resolution (required resolution check to be enabled).
    * @return E_TOO_LARGE  Requested period is too large.
    *
    * @note This function will affect all channels of the timer.
    * @note Adjusts Timer pre-scaler to appropriate value.
    * @note The counter load value (CNTIN) is cleared
    * @note The counter modulo value (MOD) is modified to obtain the requested period
    * @note The Timer is stopped while being modified.
    * @note The Timer counter is restarted from zero
    */
   static ErrorCode setPeriod(Seconds period) {
   
      uint16_t modValue = 0;
   
      uint8_t sc = tpm->SC;
   
      ErrorCode rc = calculateTimingParameters(period, sc, modValue);
   
      if (rc != E_NO_ERROR) {
         return rc;
      }
      // Disable timer to change prescaler and period
      tpm->SC = 0;
   
      // Configure for modulo operation
      tpm->MOD   = modValue;
   
      // Clear counter
      tpm->CNT   = 0;
   
      // Set prescale and enable timer
      tpm->SC  = sc;
   
      return E_NO_ERROR;
   }
   
   /**
    * Set maximum interval for input-capture or output compare.
    * Input Capture and Output Compare will be able to operate over
    * at least this period without overflow.
    *
    * @param[in] interval Interval in seconds as a float
    *
    * @return E_NO_ERROR  => success
    * @return E_TOO_SMALL  Requested period is too small for resolution (required resolution check to be enabled).
    * @return E_TOO_LARGE  Requested period is too large.
    *
    * @note This function will affect all channels of the timer.
    * @note Adjusts Timer pre-scaler to appropriate value.
    * @note TPM counter is configured for free-running mode i.e. 0-65535
    * @note The Timer is stopped while being modified.
    * @note The Timer counter is restarted from zero
    */
   static ErrorCode setMaximumInterval(Seconds interval) {
   
      uint16_t       modValue;
   
      uint8_t sc = tpm->SC;
   
      ErrorCode rc = calculateTimingParameters(interval, sc, modValue);
      if (rc != E_NO_ERROR) {
         return rc;
      }
   
      // Disable timer to change prescaler and period
      tpm->SC = 0;
   
      // Configure for free-running mode
      // This is the usual value for IC or OC set-up
      tpm->MOD   = 0_ticks;
   
      // Clear counter
      tpm->CNT   = 0;
   
      // Set prescale and enable timer
      tpm->SC  = sc;
   
      return E_NO_ERROR;
   }

   /**
    * Get frequency of timer tick
    *
    * @return Timer frequency in Hz
    */
   static float getTickFrequencyAsFloat() {
   
      // Calculate timer prescale factor
      float prescaleFactor = 1<<((tpm->SC&TPM_SC_PS_MASK)>>TPM_SC_PS_SHIFT);
   
      return Info::getInputClockFrequency((TpmClockSource)(tpm->SC&TPM_SC_CMOD_MASK))/prescaleFactor;
   }
   
   /**
    * Get clock frequency
    *
    * @return Frequency as a uint32_t in Hz (may underflow)
    */
   static uint32_t getTickFrequencyAsInt() {
   
      // Calculate timer prescale factor
      int prescaleFactor = 1<<((tpm->SC&TPM_SC_PS_MASK)>>TPM_SC_PS_SHIFT);
   
      return Info::getInputClockFrequency((TpmClockSource)(tpm->SC&TPM_SC_CMOD_MASK))/prescaleFactor;
   }

   /**
    * Convert time in microseconds to time in ticks
    *
    * @param[in] time Time in microseconds
    *
    * @return Time in ticks
    *
    * @note Assumes prescale has been chosen as a appropriate value. Rudimentary range checking.
    * @note Will set error code if calculated value is less the Timer minimum resolution
    */
   static Ticks convertMicrosecondsToTicks(int time) {
   
      // Calculate period
      uint32_t tickRate = getTickFrequencyAsInt();
      uint64_t rv       = (static_cast<uint64_t>(time)*tickRate)/1000000;
      usbdm_assert(rv <= 0xFFFFUL, "Interval is too long");
      if (rv > 0xFFFFUL) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      if (rv < Info::minimumInterval) {
         // Attempt to set too short a period
         setErrorCode(E_TOO_SMALL);
      }
      return (unsigned)rv;
   }
   
   /**
    * Converts time in seconds to time in ticks
    *
    * @param[in] seconds Time interval in seconds
    *
    * @return Time in ticks
    *
    * @note Assumes prescale has been chosen as a appropriate value (see setMaximumInterval()). 

    * @note Will set error code if calculated value is less the minimum resolution
    */
   static Ticks convertSecondsToTicks(Seconds seconds) {
   
      // Calculate period
      float    tickRate = getTickFrequencyAsFloat();
      uint64_t rv       = rintf((float)seconds*tickRate);
      usbdm_assert(rv <= 0xFFFFUL, "Interval is too long");
      if (rv > 0xFFFFUL) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      if (rv < Info::minimumInterval) {
         // Attempt to set too short a period
         setErrorCode(E_TOO_SMALL);
      }
      return (unsigned)rv;
   }
   
   /**
    * Convert time in ticks to time in microseconds
    *
    * @param[in] timeInTicks Time in ticks
    *
    * @return Time in microseconds
    *
    * @note Assumes prescale has been chosen as a appropriate value. Rudimentary range checking.
    */
   static uint32_t convertTicksToMicroseconds(Ticks timeInTicks) {
   
      // Calculate period
      uint64_t rv = (static_cast<uint64_t>((unsigned)timeInTicks)*1000000)/getTickFrequencyAsInt();
#ifdef DEBUG_BUILD
      if (rv > 0xFFFFUL) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      if (rv == 0) {
         // Attempt to set too short a period
         setErrorCode(E_TOO_SMALL);
      }
#endif
      return rv;
   }
   
   /**
    * Convert time in ticks to time in milliseconds
    *
    * @param[in] timeInTicks Time in ticks
    *
    * @return Time in milliseconds
    *
    * @note Assumes prescale has been chosen as a appropriate value. Rudimentary range checking.
    */
   static uint32_t convertTicksToMilliseconds(Ticks timeInTicks) {
   
      // Calculate period
      uint64_t rv = (static_cast<uint64_t>((unsigned)timeInTicks)*1000)/getTickFrequencyAsInt();
#ifdef DEBUG_BUILD
      if (rv > 0xFFFFUL) {
         // Attempt to set too long a period
         setErrorCode(E_TOO_LARGE);
      }
      if (rv == 0) {
         // Attempt to set too short a period
         setErrorCode(E_TOO_SMALL);
      }
#endif
      return rv;
   }
   
   /**
    * Convert time in ticks to time in seconds
    *
    * @param[in] timeInTicks Time in ticks
    *
    * @return Time in seconds
    */
   static Seconds convertTicksToSeconds(Ticks timeInTicks) {
      return static_cast<float>((unsigned)timeInTicks)/getTickFrequencyAsFloat();
   }
   /**
    * Get Timer count
    *
    * @return Timer count value
    */
   static uint16_t getTime() {
      return tpm->CNT;
   }

   /**
    * Reset counter to initial value
    */
   static void resetTime() {
      // Note: writing ANY value loads CNT from CNTIN
      tpm->CNT = 0;
   }
   
   /**
    * Get timer event flags
    *
    * @return Flags indicating if an event has occurred on a channel
    *         There is one bit for each channel
    */
   static unsigned getInterruptFlags() {
      return tpm->STATUS;
   }
   
   /**
    * Clear selected timer event flags
    *
    * @param channelMask Mask indicating which channel flags to clear
    *                    There is one bit for each channel
    *
    * @note Flags will not be cleared if the channel is configured for DMA
    */
   static void clearSelectedInterruptFlags(uint32_t channelMask) {
      (void)tpm->STATUS;
      tpm->STATUS = ~channelMask;
   }
   
   /**
    * Get and clear timer event flags
    *
    * @return Flags indicating if an event has occurred on a channel
    *         There is one bit for each channel
    *
    * @note Only flags captured in the return value are cleared
    * @note Flags will not be cleared if the channel is configured for DMA
    */
   static unsigned getAndClearInterruptFlags() {
      // Note - w1c flags
      // so only flags captured in status are cleared
      unsigned status = tpm->STATUS;
      tpm->STATUS = status;
      return status;
   }
   /**
    * Enable/disable Timer Overflow interrupts
    */
   static void enableTimerOverflowInterrupts() {
      tpm->SC = tpm->SC | TPM_SC_TOIE_MASK;
   }
   
   /**
    * Disable Timer Overflow interrupts
    */
   static void disableTimerOverflowInterrupts() {
      tpm->SC = tpm->SC & ~TPM_SC_TOIE_MASK;
   }

   /*
    * *****************************************************************
    *          Channel functions
    * *****************************************************************
    */
   /**
    * Set PWM duty cycle.
    * Higher precision float version
    *
    * @param[in] dutyCycle  Duty-cycle as percentage (float)
    * @param[in] channel    Timer channel
    *
    * @note The actual CnV register update may be delayed by the register synchronisation mechanism
    */
   static void setDutyCycle(float dutyCycle, int channel) {
      if (tpm->SC&TPM_SC_CPWMS_MASK) {
         tpm->CONTROLS[channel].CnV  = round((dutyCycle*tpm->MOD)/100.0f);
      }
      else {
         tpm->CONTROLS[channel].CnV  = round((dutyCycle*(tpm->MOD+1))/100.0f);
      }
   }
   
   /**
    * Set PWM duty cycle
    *
    * @param[in] dutyCycle  Duty-cycle as percentage
    * @param[in] channel    Timer channel
    *
    * @note The actual CnV register update may be delayed by the register synchronisation mechanism
    */
   static void setDutyCycle(int dutyCycle, int channel) {
      if (tpm->SC&TPM_SC_CPWMS_MASK) {
         tpm->CONTROLS[channel].CnV  = (dutyCycle*tpm->MOD)/100;
      }
      else {
         tpm->CONTROLS[channel].CnV  = (dutyCycle*(tpm->MOD+1))/100;
      }
   }
   
   /**
    * Set PWM high time in ticks
    * Assumes value is less than period
    *
    * @param[in] highTime   PWM high time in ticks
    * @param[in] channel    Timer channel
    *
    * @return E_NO_ERROR on success
    * @return E_TOO_LARGE on success
    *
    * @note The actual CnV register update may be delayed by the register synchronisation mechanism
    */
   static ErrorCode setHighTime(Ticks highTime, int channel) {
   
      if (tpm->SC&TPM_SC_CPWMS_MASK) {
         // In CPWM the pulse width is doubled
         highTime = (highTime+1_ticks)/2U;
      }
#ifdef DEBUG_BUILD
      if ((unsigned)highTime > tpm->MOD) {
         return setErrorCode(E_TOO_LARGE);
      }
#endif
      tpm->CONTROLS[channel].CnV  = (unsigned)highTime;
      return E_NO_ERROR;
   }
   
   /**
    * Get Timer event time
    *
    * @param[in] channel    Timer channel
    *
    * @return Absolute time of last event in ticks i.e. value from timer event register
    */
   static Ticks getEventTime(int channel) {
      return (unsigned)(tpm->CONTROLS[channel].CnV);
   }
   
   /**
    * Set Timer event time
    *
    * This value is write-buffered and updated by Cnv synchronisation.
    *
    * @param[in] eventTime  Absolute event time in ticks i.e. value to use as timer comparison value
    * @param[in] channel    Timer channel
    */
   static void setEventTime(Ticks eventTime, int channel) {
      tpm->CONTROLS[channel].CnV = (unsigned)eventTime;
   }
   
   /**
    * Set Timer event time relative to current event time
    *
    * @param[in] offset     Event time in ticks relative to current event time (i.e. Timer channel CnV value)
    * @param[in] channel    Timer channel
    *
    * @note This value is write-buffered and updated by CnV synchronisation.
    */
   static void setDeltaEventTime(Ticks offset, int channel) {
      tpm->CONTROLS[channel].CnV = tpm->CONTROLS[channel].CnV + (unsigned)offset;
   }
   
   /**
    * Set Timer event time relative to current timer count value
    *
    * @param[in] offset     Event time in ticks relative to current time (i.e. Timer CNT value)
    * @param[in] channel    Timer channel
    *
    * @note This value is write-buffered and updated by CnV synchronisation.
    */
   static void setRelativeEventTime(Ticks offset, int channel) {
      tpm->CONTROLS[channel].CnV = tpm->CNT + (unsigned)offset;
   }
   
   /**
    * Set PWM high time in seconds
    *
    * @param[in] highTime   PWM high time in seconds
    * @param[in] channel    Timer channel
    *
    * @return E_NO_ERROR on success
    *
    * @note The actual CnV register update may be delayed by the TPM register synchronisation mechanism
    */
   static ErrorCode setHighTime(Seconds highTime, int channel) {
      return setHighTime(convertSecondsToTicks(highTime), channel);
   }
   
   /**
    * Enable interrupts in NVIC
    */
   static void enableNvicInterrupts() {
      NVIC_EnableIRQ(Info::irqNums[0]);
   }

   /**
    * Enable and set priority of interrupts in NVIC
    *
    * @param[in]  nvicPriority  Interrupt priority
    *
    * @note Any pending interrupts are cleared before enabling.
    */
   static void enableNvicInterrupts(NvicPriority nvicPriority) {
      enableNvicInterrupt(Info::irqNums[0], nvicPriority);
   }

   /**
    * Disable interrupts in NVIC
    */
   static void disableNvicInterrupts() {
      NVIC_DisableIRQ(Info::irqNums[0]);
   }

public:
   /**
    * Template class representing a timer channel
    *
    * Example
    * @code
    * // Instantiate the timer and channel being used (for TPM0 & channel 6)
    * using Tmr      = USBDM::Tpm0;
    * using Tmr0_ch6 = Tmr::Channel<6>;
    *
    * // Enable and initialise timer with initial alignment
    * Tmr::configure(TpmMode_LeftAlign);
    *
    * // Change timer period (in ticks) (affects ALL channels of timer)
    * Tmr::setPeriod(500);
    *
    * // Configure channel as PWM
    * Tmr0_ch6::configure(TpmChannelMode_PwmHighTruePulses);
    *
    * // Change duty cycle (in percent)
    * Tmr0_ch6.setDutyCycle(45);
    * @endcode
    *
    * @tparam channel TPM timer channel
    */
   template <int channel>
   class Channel : public PcrTable_T<Info, limitIndex<Info>(channel)>, public TpmChannel {

   private:
      TpmBase::CheckChannel<Info, channel> check;

   private:
      /**
       * This class is not intended to be instantiated
       */
      Channel(const Channel&) = delete;
      Channel(Channel&&) = delete;

   public:
      typedef typename Info::ChannelInit ChannelInit;

      constexpr Channel() : TpmChannel(Info::baseAddress, channel) {}
      virtual ~Channel() = default;

   protected:
      /**
       * Get frequency of timer tick
       *
       * @return Timer frequency in Hz
       */
      virtual float getInputClockFrequencyVirtual(TpmClockSource tpmClockSource) const override {
         return Info::getInputClockFrequency(tpmClockSource);
      }

   public:
      // GPIO associated with this channel
      template<Polarity polarity>
      using Gpio = GpioTable_T<Info, limitIndex<Info>(channel), polarity>; // Inactive is high

      /** Allow access to PCR of associated pin */
      using Pcr = PcrTable_T<Info, limitIndex<Info>(channel)>;

      /** Allow access owning TPM */
      using OwningTpm = TpmBase_T<Info>;

      /** Allow access to FTM hardware */
      static constexpr HardwarePtr<TPM_Type> tpm = Info::baseAddress;

      /** @return Base address of TPM.CONTROL struct as uint32_t */
      static constexpr uint32_t tpmCONTROL() { return tpmBase() + offsetof(TPM_Type, CONTROLS[channel]); }

      /** @return Address of TPM.CONTROL.CnSC as uint32_t */
      static constexpr uint32_t tpmCnSC() { return tpmCONTROL()+0; }

      /** @return Address of TPM.CONTROL.CnV as uint32_t */
      static constexpr uint32_t tpmCnV() { return tpmCONTROL()+sizeof(uint32_t); }

      /**
       * Structure for TPM channel.
       */
      struct TpmChannelRegs {
         __IO uint32_t  CnSC; /**< 000C: Channel  Status and Control */
         __IO uint32_t  CnV;  /**< 0010: Channel  Value              */
      };

      /**
       * Allows access to TPM channel registers.
       *
       * @return Reference to the TPM channel registers
       */
      static __attribute__((always_inline)) volatile TpmChannelRegs &channelRegs() {
         return *reinterpret_cast<TpmChannelRegs *>(&OwningTpm::tpm->CONTROLS[CHANNEL]);
      }

      /** Timer channel number */
      static constexpr unsigned CHANNEL      = channel;

      /** Mask for Timer channel */
      static constexpr uint32_t CHANNEL_MASK = 1<<channel;

      /**
       * Configure channel and sets mode.
       *
       * @note This method has the side-effect of clearing the register update synchronisation i.e.
       *       pending CnV register updates are discarded.
       */
      static void defaultConfigure() {
         OwningTpm::configureChannel(OwningTpm::DefaultChannelInitValues[channel]);
      }

      /**
       * Configure channel
       *
       * @note This method has the side-effect of clearing the register update synchronisation i.e.
       *       pending CnV register updates are discarded.
       */
      static void configure(ChannelInit channelInit) {
         OwningTpm::configureChannel(channelInit);
      }
      
   
      /**
       * Set Action on Channel Event
       *
       * @param tpmChannelAction Enable interrupt on channel event
       *
       * @note This method has the side-effect of clearing the register update synchronisation i.e.
       *       pending CnV register updates are discarded.
       */
      static  void setAction(TpmChannelAction tpmChannelAction) {
         tpm->CONTROLS[channel].CnSC = (tpm->CONTROLS[channel].CnSC & ~TPM_CnSC_CHIE_MASK) | tpmChannelAction;
      }

      /**
       * Configure channel.
       * No affect on shared settings of owning Timer
       *
       * @param[in] tpmChannelMode    Mode of operation for channel
       * @param[in] tpmChannelAction  Whether to enable the interrupt or DMA function on this channel
       *
       * @note This method has the side-effect of clearing the register update synchronisation i.e.
       *       pending CnV register updates are discarded.
       */
      static  void configure(
            TpmChannelMode    tpmChannelMode,
            TpmChannelAction  tpmChannelAction = TpmChannelAction_None) {
   
         tpm->CONTROLS[channel].CnSC = tpmChannelMode|tpmChannelAction;
      }
   
      /**
       * Disables timer channel (sets mode to TpmChannelMode_Disabled)
       */
      static  void disable() {
         setMode(TpmChannelMode_Disabled);
      }
   
      /**
       * Get channel mode.
       *
       * @return Current mode of operation for the channel
       */
      static  TpmChannelMode getMode() {
         return static_cast<TpmChannelMode>(tpm->CONTROLS[channel].CnSC &
               (TPM_CnSC_MS_MASK|TPM_CnSC_ELS_MASK));
      }
   
      /**
       * Set channel mode
       *
       * @param[in] tpmChannelMode      Mode of operation for channel
       *
       * @note This method has the side-effect of clearing the register update synchronisation i.e.
       *       pending CnV register updates are discarded.
       */
      static  void setMode(TpmChannelMode tpmChannelMode) {
         tpm->CONTROLS[channel].CnSC =
               (tpm->CONTROLS[channel].CnSC & ~(TPM_CnSC_MS_MASK|TPM_CnSC_ELS_MASK))|tpmChannelMode;
      }
   
      /**
       * Set PWM high time in ticks.
       * Assumes value is less than period
       *
       * @param[in] highTime   PWM high time in ticks
       *
       * @return E_NO_ERROR on success
       *
       * @note The actual CnV register update will be delayed by the register synchronisation mechanism
       */
      static  ErrorCode setHighTime(Ticks highTime) {
         return OwningTpm::setHighTime(highTime, channel);
      }
   
      /**
       * Set PWM high time in seconds.
       * Higher precision float version
       *
       * @param[in] highTime   PWM high time in seconds
       *
       * @return E_NO_ERROR on success
       *
       * @note The actual CnV register update will be delayed by the register synchronisation mechanism
       */
      static  ErrorCode setHighTime(Seconds highTime) {
         return OwningTpm::setHighTime(highTime, channel);
      }
      /**
       * Set PWM duty cycle.
       *
       * @param[in] dutyCycle  Duty-cycle as percentage
       *
       * @note The actual CnV register update will be delayed by the register synchronisation mechanism
       */
      static  void setDutyCycle(int dutyCycle) {
         OwningTpm::setDutyCycle(dutyCycle, channel);
      }
   
      /**
       * Set PWM duty cycle
       *
       * @param[in] dutyCycle  Duty-cycle as percentage
       *
       * @note The actual CnV register update will be delayed by the register synchronisation mechanism
       */
      static  void setDutyCycle(float dutyCycle) {
         OwningTpm::setDutyCycle(dutyCycle, channel);
      }
   
      /**
       * Set Timer event time.
       *
       * @param[in] offset  Event time in ticks relative to current event time (i.e. Timer channel CnV value)
       *
       * @note The actual CnV register update will be delayed by the register synchronisation mechanism
       */
      static  void setDeltaEventTime(Ticks offset) {
         OwningTpm::setDeltaEventTime(offset, channel);
      }
   
      /**
       * Set Timer event time relative to current timer count value.
       *
       * @param[in] offset  Event time in ticks relative to current time (i.e. Timer CNT value)
       *
       * @note The actual CnV register update will be delayed by the register synchronisation mechanism
       */
      static  void setRelativeEventTime(Ticks offset) {
         OwningTpm::setRelativeEventTime(offset, channel);
      }
   
      /**
       * Set Absolute Timer event time.
       *
       * @param[in] eventTime  Absolute event time in ticks i.e. value to use as timer comparison value
       *
       * @note The actual CnV register update will be delayed by the register synchronisation mechanism
       */
      static  void setEventTime(Ticks eventTime) {
         OwningTpm::setEventTime(eventTime, channel);
      }
   
      /**
       * Get Absolute Timer event time.
       *
       * @return Absolute time of last event in ticks i.e. value from timer event register
       */
      static  Ticks getEventTime() {
         return OwningTpm::getEventTime(channel);
      }
   
      /**
       * Get Timer interrupt/event flag.
       *
       * @return true  Indicates an event has occurred on a channel
       * @return false Indicates no event has occurred on a channel since last polled
       */
      static  bool getInterruptFlag() {
         return (tpm->STATUS&CHANNEL_MASK) != 0;
      }
   
      /**
       * Get and Clear Timer channel interrupt flag.
       *
       * @return true  Indicates an event has occurred on a channel
       * @return false Indicates no event has occurred on a channel since last polled
       *
       * @note Only flags captured in the return value are cleared
       */
      static  bool getAndClearInterruptFlag() {
         // Note - w1c flags
         // so only flags captured in status are cleared
         bool status = (tpm->STATUS&CHANNEL_MASK) != 0;
         tpm->STATUS = CHANNEL_MASK;
         return status;
      }
   
      /**
       * Clear interrupt flag on channel.
       */
      static  void clearInterruptFlag() {
         // Note - w1c flags
         tpm->CONTROLS[CHANNEL].CnSC = TPM_CnSC_CHF_MASK;
      }


      /*******************************
       *  PIN Functions
       *******************************/
      /**
       * Set callback for Pin IRQ.
       *
       * @param[in] callback The function to call on Pin interrupt.\n
       *                     nullptr to indicate none
       *
       * @note There is a single callback function for all pins on the related port.
       */
      static __attribute__((always_inline)) void setPinCallback(PinCallbackFunction callback) {
         TpmBase::CheckChannelIsMappedToPinOnly<Info, channel>::check();
         static_assert(Pcr::HANDLER_INSTALLED, "Gpio associated with TPM channel not configured for PIN interrupts - Modify Configure.usbdm");
         Pcr::setPinCallback(callback);
      }

#if defined(PORT_PCR_ODE_MASK) and defined (PORT_PCR_SRE_MASK)
   /**
    * @brief
    * Set subset of Pin Control Register Attributes associated with output direction \n
    * Mux value is set appropriately for the pin function being used. Other attributes are cleared.
    * Assumes clock to the port has already been enabled
    *
    * @param[in] pinDriveStrength One of PinDriveStrength_Low, PinDriveStrength_High
    * @param[in] pinDriveMode     One of PinDriveMode_PushPull, PinDriveMode_OpenDrain
    * @param[in] pinSlewRate      One of PinSlewRate_Slow, PinSlewRate_Fast
    */
   static void setOutput(
         PinDriveStrength  pinDriveStrength  = Pcr::defaultPcrValue,
         PinDriveMode      pinDriveMode      = Pcr::defaultPcrValue,
         PinSlewRate       pinSlewRate       = Pcr::defaultPcrValue) {

      TpmBase::CheckChannelIsMappedToPinOnly<Info, channel>::check();

#ifdef TPM_SC_PWMEN0_SHIFT
      // Enable output pin in TPM
      tpm->SC = tpm->SC | (1<<(channel+TPM_SC_PWMEN0_SHIFT));
#endif
      Pcr::setPCR(pinDriveStrength|pinDriveMode|pinSlewRate);
   }
#elif defined(PORT_PCR_ODE_ASK)
   /**
    * @brief
    * Set subset of Pin Control Register Attributes associated with output direction \n
    * Mux value is set appropriately for the pin function being used. Other attributes are cleared.
    * Assumes clock to the port has already been enabled
    *
    * @param[in] pinDriveStrength One of PinDriveStrength_Low, PinDriveStrength_High
    * @param[in] pinDriveMode     One of PinDriveMode_PushPull, PinDriveMode_OpenDrain
    */
   static void setOutput(
         PinDriveStrength  pinDriveStrength  = Pcr::defaultPcrValue,
         PinDriveMode      pinDriveMode      = Pcr::defaultPcrValue) {

      TpmBase::CheckChannelIsMappedToPinOnly<Info, channel>::check();

#ifdef TPM_SC_PWMEN0_SHIFT
      // Enable output pin in TPM
      tpm->SC = tpm->SC | (1<<(channel+TPM_SC_PWMEN0_SHIFT));
#endif
      Pcr::setPCR(pinDriveStrength|pinDriveMode);
   }
#elif defined(PORT_PCR_SRE_MASK)
   /**
    * @brief
    * Set subset of Pin Control Register Attributes associated with output direction \n
    * Mux value is set appropriately for the pin function being used. Other attributes are cleared.
    * Assumes clock to the port has already been enabled
    *
    * @param[in] pinDriveStrength One of PinDriveStrength_Low, PinDriveStrength_High
    * @param[in] pinSlewRate      One of PinSlewRate_Slow, PinSlewRate_Fast
    */
   static void setOutput(
         PinDriveStrength  pinDriveStrength  = Pcr::defaultPcrValue,
         PinSlewRate       pinSlewRate       = Pcr::defaultPcrValue) {

      TpmBase::CheckChannelIsMappedToPinOnly<Info, channel>::check();

#ifdef TPM_SC_PWMEN0_SHIFT
      // Enable output pin in TPM
      tpm->SC = tpm->SC | (1<<(channel+TPM_SC_PWMEN0_SHIFT));
#endif
      Pcr::setPCR(pinDriveStrength|pinSlewRate);
   }
#else
   /**
    * @brief
    * Set subset of Pin Control Register Attributes associated with output direction \n
    * Mux value is set appropriately for the pin function being used. Other attributes are cleared.
    * Assumes clock to the port has already been enabled
    *
    * @param[in] pinDriveStrength One of PinDriveStrength_Low, PinDriveStrength_High
    */
   static void setOutput(
         PinDriveStrength  pinDriveStrength  = Pcr::defaultPcrValue) {

      TpmBase::CheckChannelIsMappedToPinOnly<Info, channel>::check();

#ifdef TPM_SC_PWMEN0_SHIFT
      // Enable output pin in TPM
      tpm->SC = tpm->SC | (1<<(channel+TPM_SC_PWMEN0_SHIFT));
#endif

      Pcr::setPCR(pinDriveStrength);
   }
#endif

      /**
       * @brief
       * Set subset of Pin Control Register Attributes associated with input direction \n
       * Mux value is set appropriately for the pin function being used. Other attributes are cleared.\n
       * The clock to the port will be enabled before changing the PCR.
       *
       * @param[in] pinPull          One of PinPull_None, PinPull_Up, PinPull_Down
       * @param[in] pinAction        One of PinAction_None, etc
       * @param[in] pinFilter        One of PinFilter_None, PinFilter_Passive
       *
       *  @note see also configureDigitalFilter(), enableDigitalFilter(), disableDigitalFilter()
       */
      static void setInput(
            PinPull           pinPull           = Pcr::defaultPcrValue,
            PinAction         pinAction         = Pcr::defaultPcrValue,
            PinFilter         pinFilter         = Pcr::defaultPcrValue) {

         TpmBase::CheckChannelIsMappedToPinOnly<Info, channel>::check();
//         TpmBase::CheckChannelExistsAndMapped<Info, channel>::check(); // More noisy errors

#ifdef TPM_SC_PWMEN0_SHIFT
         // Disable output pin in TPM
         tpm->SC = tpm->SC & ~(1<<(channel+TPM_SC_PWMEN0_SHIFT));
#endif

         Pcr::setInput(pinPull,pinAction,pinFilter);
      }

   };

   /**
    * Configure with settings from Configure.usbdmProject.
    */
   static void defaultConfigure() {

     configure(Info::DefaultInitValue);


     NVIC_SetPriority(Info::irqNums[0], Info::irqLevel);
   }

};

template<class Info> typename Info::CallbackFunction TpmBase_T<Info>::sCallback           = unhandledCallback;

#ifdef TPM_QDCTRL_QUADEN_MASK
/**
 *  Quadrature Decoder Mode\n
 *  Selects the encoding mode used in the Quadrature Decoder mode.
 */
enum TpmQuadratureMode {
   TpmQuadratureMode_Phase_AB_Mode        = TPM_QDCTRL_QUADMODE(0),   //!< Phase A and phase B encoding mode.
   TpmQuadratureMode_Count_Direction_Mode = TPM_QDCTRL_QUADMODE(1),   //!< Count and direction encoding mode.
};

/**
 * Template class representing a TPM configured as a Quadrature decoder
 *
 * @tparam info      Information class for TPM
 *
 * @code
 *  using TpmQuadDecoder = TpmQuadDecoder_T<Tpm0Info>;
 *
 *  // Enable decoder
 *  TpmQuadDecoder::configure();
 *
 *  // Set pin filters
 *  TpmQuadDecoder::enableFilter(15);
 *
 *  // Reset position to zero
 *  // Movement will be +/- relative to this initial position
 *  TpmQuadDecoder::resetPosition();
 *
 *  for(;;) {
 *     console.write("Position =").writeln(QuadDecoder.getPosition());
 *  }
 * @endcode
 */
template <class Info>
class TpmQuadDecoder_T : protected TpmBase_T<Info> {

private:
   TpmQuadDecoder_T(const TpmQuadDecoder_T&) = delete;
   TpmQuadDecoder_T(TpmQuadDecoder_T&&) = delete;

   TpmBase::CheckChannel<typename Info::InfoQUAD, 0> checkQ0;
   TpmBase::CheckChannel<typename Info::InfoQUAD, 1> checkQ1;

public:
   // Default constructor
   TpmQuadDecoder_T() = default;

   void setCallback(typename Info::CallbackFunction theCallback) {
      TpmBase_T<Info>::setCallback(theCallback);
   }

   using QuadInit = typename Info::QuadInit;

   static constexpr QuadInit DefaultInitValue = Info::DefaultQuadInitValue;

   /** Hardware instance pointer */
   static constexpr HardwarePtr<TPM_Type> tpm = Info::baseAddress;

   /** Allow more convenient access associated Tpm */
   using OwningTpm = TpmBase_T<Info>;

   /** Allow access to PCR of associated phase-A pin */
   using Pcr0 = PcrTable_T<typename Info::InfoQUAD, 0>;

   /** Allow access to PCR of associated phase-B pin */
   using Pcr1 = PcrTable_T<typename Info::InfoQUAD, 1>;

   /**
    * Set Pin Control Register (PCR) values for PHA and PHB inputs.
    * This will map the pin to the Quadrature function (mux value) \n
    * The clock to the port will be enabled before changing the PCR
    *
    * @param[in] pinPull          One of PinPull_None, PinPull_Up, PinPull_Down
    * @param[in] pinAction        One of PinAction_None, etc (defaults to PinAction_None)
    * @param[in] pinFilter        One of PinFilter_None, PinFilter_Passive (defaults to PinFilter_None)
    */
   static void setInput(
         PinPull           pinPull           = Pcr0::defaultPcrValue,
         PinAction         pinAction         = Pcr0::defaultPcrValue,
         PinFilter         pinFilter         = Pcr0::defaultPcrValue) {

      Pcr0::setPCR(pinPull|pinAction|pinFilter);
      Pcr1::setPCR(pinPull|pinAction|pinFilter);
   }

   /**
    * Set TOI Callback function\n
    * Note that one callback is shared by all channels of the TPM
    *
    * @param[in] theCallback Callback function to execute when timer overflows. \n
    *                        nullptr to indicate none
    */
   static __attribute__((always_inline)) void setTimerOverflowCallback(typename Info::CallbackFunction theCallback) {
      OwningTpm::setTimerOverflowCallback(theCallback);
   }

   /**
    * Enable Timer Overflow interrupts
    */
   static __attribute__((always_inline)) void enableTimerOverflowInterrupts() {
      OwningTpm::enableTimerOverflowInterrupts();
   }

   /**
    * Disable Timer Overflow interrupts
    */
   static __attribute__((always_inline)) void disableTimerOverflowInterrupts() {
      OwningTpm::disableTimerOverflowInterrupts();
   }

   /**
    * Enable interrupts in NVIC
    */
   static void enableNvicInterrupts() {
      NVIC_EnableIRQ(Info::irqNums[0]);
   }

   /**
    * Enable and set priority of interrupts in NVIC
    *
    * @param[in]  nvicPriority  Interrupt priority
    *
    * @note Any pending interrupts are cleared before enabling.
    */
   static void enableNvicInterrupts(NvicPriority nvicPriority) {
      enableNvicInterrupt(Info::irqNums[0], nvicPriority);
   }

   /**
    * Disable interrupts in NVIC
    */
   static void disableNvicInterrupts() {
      NVIC_DisableIRQ(Info::irqNums[0]);
   }

   /**
    * Configures all mapped pins associated with this peripheral
    */
   static void configureAllPins() {
      // Configure pins
      Info::InfoQUAD::initPCRs();
   }

   /**
    * Disabled all mapped pins associated with TPM
    *
    * @note Only the lower 16-bits of the PCR registers are modified
    */
   static void disableAllPins() {
      // Configure pins
      Info::InfoQUAD::clearPCRs();
   }

   /**
    * Basic enable of TPM
    * Includes enabling clock and configuring all pins if mapPinsOnEnable is selected in configuration
    */
   static void enable() {
      // Enable clock to peripheral
      Info::enableClock();

      if constexpr (Info::mapPinsOnEnable) {
         configureAllPins();
      }
   }

   /**
    * Disables the clock to TPM and all mappable pins
    */
   static void disable() {

      disableNvicInterrupts();

      if constexpr (Info::mapPinsOnEnable) {
         disableAllPins();
      }

      // Disable TPM (clock source disabled)
      tpm->QDCTRL = 0;

      // Disable clock to peripheral interface
      Info::disableClock();
   }

   static ErrorCode configure(const typename Info::QuadInit &quadInit) {

      // Assertions placed here so only checked if TpmQuadDecoder actually used
      static_assert(Info::InfoQUAD::info[0].gpioBit >= 0, "TpmQuadDecoder PHA is not mapped to a pin - Modify Configure.usbdm");
      static_assert(Info::InfoQUAD::info[1].gpioBit >= 0, "TpmQuadDecoder PHB is not mapped to a pin - Modify Configure.usbdm");

      // Enable peripheral clock and map pins
      enable();

      if constexpr (Info::irqHandlerInstalled) {
         // Only set call-back if feature enabled and non-null
         if (quadInit.callbackFunction != nullptr) {
            TpmBase_T<Info>::setCallback(quadInit.callbackFunction);
         }
         enableNvicInterrupts(quadInit.irqlevel);
      }

      // Disable timer to change clock (unable to switch directly between clock sources)
      tpm->SC  = 0;

      // End value for counter
      tpm->MOD =0;

      // Restart counter
      tpm->CNT = 0;

      // Configure timer
      tpm->FILTER = quadInit.qdfilter;
      tpm->SC     = quadInit.sc;
      tpm->QDCTRL = quadInit.qdctrl;

      return E_NO_ERROR;
   }

   /**
    * Basic configuration of Quadrature decoder.
    * Includes configuring all pins if
    * mapPinsOnEnable setting is true
    *
    * @param tpmPrescale       Prescale value applied to the output of the quadrature decode before the counter.
    * @param tpmQuadratureMode Selects the encoding mode used to decode the input changes.
    */
   static void configure(
         TpmPrescale       tpmPrescale       = TpmPrescale_DivBy1,
         TpmQuadratureMode tpmQuadratureMode = TpmQuadratureMode_Phase_AB_Mode
         ) {
      // Assertions placed here so only checked if TpmQuadDecoder actually used
      static_assert(Info::InfoQUAD::info[0].gpioBit >= 0, "TpmQuadDecoder PHA is not mapped to a pin - Modify Configure.usbdm");
      static_assert(Info::InfoQUAD::info[1].gpioBit >= 0, "TpmQuadDecoder PHB is not mapped to a pin - Modify Configure.usbdm");

      enable();

      // Disable so immediate effect
      tpm->SC = 0;
      (void)tpm->SC;
      tpm->SC = TpmClockSource_Disabled|tpmPrescale;

      tpm->QDCTRL =
            TPM_QDCTRL_QUADEN_MASK|      // Enable Quadrature decoder
            tpmQuadratureMode;           // Quadrature mode
      tpm->CONF   = TPM_CONF_DBGMODE(3);
   }

   /**
    * Reset position to zero
    */
   static void resetPosition() {
      // Note: writing ANY value clears CNT (cannot set value)
      tpm->CNT = 0;
   }

   /**
    * Get Quadrature decoder position
    *
    * @return Signed number representing position relative to reference location
    *
    * @note This can be viewed as a signed number +/- relative to the initial position.
    * @note This can be viewed as an unsigned number counting up from 0
    *       with overflow at 0xFFFF and underflow at 0.
    */
   static int16_t getPosition() {
      return (int16_t)(tpm->CNT);
   }

   /**
    * Get Quadrature decoder overflow direction.
    * This would be used in the overflow callback.
    *
    * @return Timer overflow direction. true => increasing, false => decreasing.
    *
    * @note Overflow occurs at MOD -> CNTIN, Underflow occurs at CNTIN -> MOD.
    */
   static bool getOverflowDirection() {
      return (bool)(tpm->QDCTRL & TPM_QDCTRL_TOFDIR_MASK);
   }
};
#endif // defined(TPM_QDCTRL_QUADEN_MASK)

/**
* Class representing TPM0
*/
class Tpm0 : public TpmBase_T<Tpm0Info> {};

/**
* Class representing TPM1
*/
class Tpm1 : public TpmBase_T<Tpm1Info> {};


// No QUAD declarations found
/**
 * End TPM_Group
 * @}
 */

} // End namespace USBDM

#endif /* HEADER_TPM_H */

